config/routes.rb
Rails.application.routes.draw do
  # get 'reviews/new'
  # get 'reviews/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # THE FOLLOWING GETS CREATED WHEN GENERATING THE CONTROLLER INCL ALL CRUD METHODS
  # get 'restaurants/index'
  # get 'restaurants/show'
  # get 'restaurants/new'
  # get 'restaurants/create'
  # get 'restaurants/edit'
  # get 'restaurants/update'
  # get 'restaurants/destroy'
  # BUT NOT NEEDED AS WE USE RESOURCES (BUT NOT ALL OF THEM)
  resources :restaurants, only: [:index, :new, :show, :create ] do
    # lets you start from a particular restaurant: a /restaurants/:restaurant_id
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy # this dependent destroy makes sure review get deleted when restos get deleted
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :name, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :find_task, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params) # ivar since its used in the the formpartial...
    if @restaurant.save
      redirect_to restaurant_path(@restaurant.id)
    else
      render(:new) #rendering does not execute the new method, instead it only uses the view of new
    end
  end

  # def edit
  # end

  # def update
  # end

  # def destroy
  # end
  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def find_task
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id]) # params is a hash and we have to call it by the right id
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

    private
    def review_params
      params.require(:review).permit(:rating, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">

<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>

</div>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<div class="container mt-5">

  <h1>Restaurants</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Phone Number</th>
        <th>Category</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @restaurants.each do |restaurant| %>
        <tr>
          <td><%= restaurant.name %></td>
          <td><%= restaurant.address %></td>
          <td><%= restaurant.phone_number %></td>
          <td><%= restaurant.category %></td>
          <td><%= link_to 'Show', restaurant_path(restaurant.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


  <br>
  <%= link_to 'New Restaurant', new_restaurant_path,class: "btn btn-danger" %>

</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= render 'form' %>

<%= link_to 'Back to complete list', restaurants_path(@restaurants),class: "btn btn-primary"  %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %> </h1>
<h2><%= @restaurant.address %></h2>
<h2><%= @restaurant.phone_number %></h2>
<h2><%= @restaurant.category %></h2>

<p>
    <strong>
      Reviews:
    </strong>
  </p>
  <% @restaurant.reviews.each do |review| %>
  <p><%= review.content %></p>
  <p><%= review.rating %></p>
  <hr>
  <% end %>

<%= link_to 'Back to complete list', restaurants_path(@restaurants),class: "btn btn-primary"  %>
<%= link_to 'Add a review', new_restaurant_review_path(@restaurant),class: "btn btn-default" %>

app/views/reviews/_form.html.erb
<div class="container">
<h1>Add a review for <%= @restaurant.name %></h1>
<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

</div>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<%= render 'form' %>

<%= link_to 'Back to complete list', restaurants_path(@restaurants),class: "btn btn-primary"  %>